name: API Explorer CI
on:
  pull_request:

  push:
    branches:
      - main

  workflow_dispatch:

env:
  TS_JUNIT_OUTPUT_DIR: results/apix

jobs:
  unit:
    name: Unit - ${{ matrix.os }} / Node ${{ matrix.node-version }}
    env:
      JEST_JUNIT_OUTPUT_DIR: results/apix
      JEST_JUNIT_OUTPUT_NAME: ${{ matrix.os }}.apix${{ matrix.node-version }}.xml
    runs-on: ${{ matrix.os }}-latest

    strategy:
      matrix:
        os:
          - ubuntu
        node-version: [12.x]

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Repo Checkout
        uses: actions/checkout@v2

      - uses: tony84727/changed-file-filter@v0.2.0
        id: filter
        with:
        # head: optional head commit SHA, default to ${{ github.event.pull_request.head.sha || github.sha }}
        # base: optional base commit SHA, default to ${{ github.event.pull_request.base.sha }} or HEAD^ if not triggered by pull_request

        # filter rules in YAML format
        # <rule-name>:
        #  - <glob expression>
          filters: |
            apix:
              - packages/code-editor/**
              - packages/run-it/**
              - packages/api-explorer/**
              - packages/extension-api-explorer/**
              - packages/extension-utils/**

      - name: Install Node ${{ matrix.node-version }}
        if: steps.filter.outputs.apix == 'true'
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        if: steps.filter.outputs.apix == 'true'
        run: |
          yarn
          yarn lint:es --quiet
          yarn lint:ts
          yarn build
          yarn dedupe:ci

      - name: Run unit tests
        if: steps.filter.outputs.apix == 'true'
        run: yarn test:apix --reporters=default --reporters=jest-junit

      - name: Upload ts unit test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: apix-test-results
          path: results/apix

  publish-test-results:
    needs: [unit]
    if: success() || failure()
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.12
        with:
          # Cosmetic issue with `check_name` being associated to the wrong
          # workflow: https://github.com/EnricoMi/publish-unit-test-result-action/issues/12
          check_name: APIX Tests
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_individual_runs: true
          hide_comments: orphaned commits
          check_run_annotations_branch: '*'
          files: 'artifacts/apix-test-results/*.xml'
