name: Hackathon CI
on:
  workflow_dispatch:

env:
  TS_JUNIT_OUTPUT_DIR: results/hackathon

jobs:
  unit:
    name: Unit - ${{ matrix.os }} / Node ${{ matrix.node-version }}
    env:
      JEST_JUNIT_OUTPUT_DIR: results/hackathon
      JEST_JUNIT_OUTPUT_NAME: ${{ matrix.os }}.apix${{ matrix.node-version }}.xml
    runs-on: ${{ matrix.os }}-latest

    strategy:
      matrix:
        os:
          - ubuntu
        node-version: [16.x]

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Repo Checkout
        uses: actions/checkout@v3

      - name: Install Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          yarn

      - name: Lint
        run: |
          yarn lint:es --quiet
          yarn lint:ts

      - name: Build all
        run: |
          yarn build
          yarn dedupe:ci

      - name: Bundle hackathon
        run: |
          yarn bundle
        working-directory: packages/hackathon
