name: Reset versions in release-please-config.json
on:
  release:
    types: published

  workflow_dispatch:

jobs:
  reset-vers:
    runs-on: ubuntu-latest
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Rewrite release-please-congfig.json
        run: |
          cp release-please-config.json.template release-please-config.json
          git add release-please-config.json
          git -c "user.name looker-open-source-automation-bot"\
              -c "user.email looker-open-source@google.com"\
              release-please-config.json
              commit "chore: reset release-please config"

      # Use the github run_id to make sure the branch name is unique.
      # On a rerun of a failed run, the run_id will be the same, so the
      # force: true makes sure it succeeds the second time.
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.LOS_AUTO_BOT_RP_TOKEN }}
          branch: losautobot/reset-release-please-config-${{ github.run_id }}
          force: true

      - name: Initialize Pull Request
        uses: gha-utilities/init-pull-request@v0.3.2
        with:
          pull_request_token: ${{ secrets.LOS_AUTO_BOT_RP_TOKEN }}
          head: losautobot/reset-release-please-config-${{ github.run_id }}
          base: main
          title: 'chore: reset release-please config'
